package DSA.OOPS.ExceptionHandling;
import java.util.*;

public class Main {
    public static void main(String[] args) {

        System.out.println((int)'A');
//        String str = "Rahul";
//        try{
//            int n= Integer.parseInt(str);
//            System.out.println(n);
//        }
//        catch(ArithmeticException e){
//            System.out.println("It Cant be proceed due to Error or exception");
//        }
//        finally {
//            System.out.println("code ran");
//        }
//        System.out.println("Main method endded");


//        String str = null;
//        try{
//            System.out.println(str.toUpperCase());
//        }
//        catch(NullPointerException e){
////            System.out.println(e);
//            System.out.println("The error is occured");
//        }

//        System.out.println(str.toUpperCase());  //This will cause NullpointerException
//        System.out.println("Main Method Started");
//        int a=10,b=0,c;
//        try {
//            c = a / b;
//            System.out.println(c);
//        }
//        catch(Exception e){
//            System.out.println(e);
//
//        }
//        System.out.println("Main Method ended");
//


    }
}
